# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-demo-registration
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: microservices-demo-registration
    spec:
      containers:
        - name: registration
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          command: ['java', '-jar', '/app.jar', 'registration', '1111']
          ports:
            - containerPort: 1111
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservices-demo-accounts
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: microservices-demo-accounts
    spec:
      containers:
        - name: accounts
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          command: ['java', '-jar', '/app.jar', 'accounts', '2222', '--registration.server.hostname=microservices-demo-registration']
          ports:
            - containerPort: 2222
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-demo-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: microservices-demo-web
    spec:
      containers:
        - name: web
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          command: ['java', '-jar', '/app.jar', 'web', '3333', '--registration.server.hostname=microservices-demo-registration']
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m