# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-jar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package --file pom.xml
    - name: Upload output jar
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: target/microservices-demo-2.1.0.RELEASE.jar
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: JUnit tests
        run: echo "passed!"
      - name: Integration tests
        run: echo "passed!"
      - name: Performance tests
        run: echo "passed!"
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag microservices-with-spring:$(date +%s)